//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormRequest", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class FormRequest : object
    {
        
        private Utilities.AdditionalDetails AdditionalDetailsField;
        
        private int FormTypeField;
        
        private Utilities.TransactionDetails TransactionDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.AdditionalDetails AdditionalDetails
        {
            get
            {
                return this.AdditionalDetailsField;
            }
            set
            {
                this.AdditionalDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FormType
        {
            get
            {
                return this.FormTypeField;
            }
            set
            {
                this.FormTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.TransactionDetails TransactionDetails
        {
            get
            {
                return this.TransactionDetailsField;
            }
            set
            {
                this.TransactionDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdditionalDetails", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class AdditionalDetails : object
    {
        
        private int CountryIdField;
        
        private string CurrencyField;
        
        private string ErrorUrlField;
        
        private Utilities.Item[] ItemsField;
        
        private string MerchantIdField;
        
        private string MerchantLogoUrlField;
        
        private string PaymentMethodsField;
        
        private string SuccessUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                this.CountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorUrl
        {
            get
            {
                return this.ErrorUrlField;
            }
            set
            {
                this.ErrorUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utilities.Item[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                this.MerchantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantLogoUrl
        {
            get
            {
                return this.MerchantLogoUrlField;
            }
            set
            {
                this.MerchantLogoUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethods
        {
            get
            {
                return this.PaymentMethodsField;
            }
            set
            {
                this.PaymentMethodsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccessUrl
        {
            get
            {
                return this.SuccessUrlField;
            }
            set
            {
                this.SuccessUrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionDetails", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class TransactionDetails : object
    {
        
        private string AcquirerIdField;
        
        private string AmountField;
        
        private string CurrencyField;
        
        private int CurrencyExponentField;
        
        private string CustomDataField;
        
        private string IPAddressField;
        
        private string MerchantIdField;
        
        private string OrderNumberField;
        
        private string SignatureField;
        
        private string SignatureMethodField;
        
        private int TransactionCodeField;
        
        private string CustomerReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AcquirerId
        {
            get
            {
                return this.AcquirerIdField;
            }
            set
            {
                this.AcquirerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CurrencyExponent
        {
            get
            {
                return this.CurrencyExponentField;
            }
            set
            {
                this.CurrencyExponentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomData
        {
            get
            {
                return this.CustomDataField;
            }
            set
            {
                this.CustomDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress
        {
            get
            {
                return this.IPAddressField;
            }
            set
            {
                this.IPAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                this.MerchantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SignatureMethod
        {
            get
            {
                return this.SignatureMethodField;
            }
            set
            {
                this.SignatureMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TransactionCode
        {
            get
            {
                return this.TransactionCodeField;
            }
            set
            {
                this.TransactionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string CustomerReference
        {
            get
            {
                return this.CustomerReferenceField;
            }
            set
            {
                this.CustomerReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class Item : object
    {
        
        private string AmountField;
        
        private string CodeField;
        
        private string CurrencyField;
        
        private string DescriptionField;
        
        private string NameField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormResponse", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class FormResponse : object
    {
        
        private string HTMLFormDataField;
        
        private string ResponseCodeField;
        
        private string ResponseCodeDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTMLFormData
        {
            get
            {
                return this.HTMLFormDataField;
            }
            set
            {
                this.HTMLFormDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCodeDescription
        {
            get
            {
                return this.ResponseCodeDescriptionField;
            }
            set
            {
                this.ResponseCodeDescriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.firstatlanticcommerce.com/gateway", ConfigurationName="Utilities.IUtilities")]
    public interface IUtilities
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/IUtilities/BuildForm", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/IUtilities/BuildFormResponse")]
        System.Threading.Tasks.Task<Utilities.FormResponse> BuildFormAsync(Utilities.FormRequest Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IUtilitiesChannel : Utilities.IUtilities, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class UtilitiesClient : System.ServiceModel.ClientBase<Utilities.IUtilities>, Utilities.IUtilities
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UtilitiesClient() : 
                base(UtilitiesClient.GetDefaultBinding(), UtilitiesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IUtilities.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UtilitiesClient(EndpointConfiguration endpointConfiguration) : 
                base(UtilitiesClient.GetBindingForEndpoint(endpointConfiguration), UtilitiesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UtilitiesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UtilitiesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UtilitiesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UtilitiesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UtilitiesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Utilities.FormResponse> BuildFormAsync(Utilities.FormRequest Request)
        {
            return base.Channel.BuildFormAsync(Request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUtilities))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUtilities))
            {
                return new System.ServiceModel.EndpointAddress("https://ecm.firstatlanticcommerce.com/PGService/Utilities.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UtilitiesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IUtilities);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UtilitiesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IUtilities);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUtilities,
        }
    }
}
