//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizeRequest", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class AuthorizeRequest : object
    {
        
        private Services.BillingDetails BillingDetailsField;
        
        private Services.CardDetails CardDetailsField;
        
        private Services.RecurringDetails RecurringDetailsField;
        
        private Services.ThreeDSecureDetails ThreeDSecureDetailsField;
        
        private Services.TransactionDetails TransactionDetailsField;
        
        private Services.ShippingDetails ShippingDetailsField;
        
        private Services.FraudDetails FraudDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.BillingDetails BillingDetails
        {
            get
            {
                return this.BillingDetailsField;
            }
            set
            {
                this.BillingDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Services.CardDetails CardDetails
        {
            get
            {
                return this.CardDetailsField;
            }
            set
            {
                this.CardDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.RecurringDetails RecurringDetails
        {
            get
            {
                return this.RecurringDetailsField;
            }
            set
            {
                this.RecurringDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.ThreeDSecureDetails ThreeDSecureDetails
        {
            get
            {
                return this.ThreeDSecureDetailsField;
            }
            set
            {
                this.ThreeDSecureDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Services.TransactionDetails TransactionDetails
        {
            get
            {
                return this.TransactionDetailsField;
            }
            set
            {
                this.TransactionDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Services.ShippingDetails ShippingDetails
        {
            get
            {
                return this.ShippingDetailsField;
            }
            set
            {
                this.ShippingDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Services.FraudDetails FraudDetails
        {
            get
            {
                return this.FraudDetailsField;
            }
            set
            {
                this.FraudDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingDetails", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class BillingDetails : object
    {
        
        private string BillToAddressField;
        
        private string BillToAddress2Field;
        
        private string BillToCityField;
        
        private string BillToCountryField;
        
        private string BillToEmailField;
        
        private string BillToFirstNameField;
        
        private string BillToLastNameField;
        
        private string BillToStateField;
        
        private string BillToTelephoneField;
        
        private string BillToZipPostCodeField;
        
        private string BillToCountyField;
        
        private string BillToMobileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillToAddress
        {
            get
            {
                return this.BillToAddressField;
            }
            set
            {
                this.BillToAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillToAddress2
        {
            get
            {
                return this.BillToAddress2Field;
            }
            set
            {
                this.BillToAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillToCity
        {
            get
            {
                return this.BillToCityField;
            }
            set
            {
                this.BillToCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillToCountry
        {
            get
            {
                return this.BillToCountryField;
            }
            set
            {
                this.BillToCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillToEmail
        {
            get
            {
                return this.BillToEmailField;
            }
            set
            {
                this.BillToEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillToFirstName
        {
            get
            {
                return this.BillToFirstNameField;
            }
            set
            {
                this.BillToFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillToLastName
        {
            get
            {
                return this.BillToLastNameField;
            }
            set
            {
                this.BillToLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillToState
        {
            get
            {
                return this.BillToStateField;
            }
            set
            {
                this.BillToStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillToTelephone
        {
            get
            {
                return this.BillToTelephoneField;
            }
            set
            {
                this.BillToTelephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillToZipPostCode
        {
            get
            {
                return this.BillToZipPostCodeField;
            }
            set
            {
                this.BillToZipPostCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string BillToCounty
        {
            get
            {
                return this.BillToCountyField;
            }
            set
            {
                this.BillToCountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string BillToMobile
        {
            get
            {
                return this.BillToMobileField;
            }
            set
            {
                this.BillToMobileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardDetails", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class CardDetails : object
    {
        
        private string CardCVV2Field;
        
        private string CardExpiryDateField;
        
        private string CardNumberField;
        
        private string IssueNumberField;
        
        private string StartDateField;
        
        private string DocumentNumberField;
        
        private int InstallmentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCVV2
        {
            get
            {
                return this.CardCVV2Field;
            }
            set
            {
                this.CardCVV2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardExpiryDate
        {
            get
            {
                return this.CardExpiryDateField;
            }
            set
            {
                this.CardExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueNumber
        {
            get
            {
                return this.IssueNumberField;
            }
            set
            {
                this.IssueNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string DocumentNumber
        {
            get
            {
                return this.DocumentNumberField;
            }
            set
            {
                this.DocumentNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Installments
        {
            get
            {
                return this.InstallmentsField;
            }
            set
            {
                this.InstallmentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringDetails", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class RecurringDetails : object
    {
        
        private string ExecutionDateField;
        
        private string FrequencyField;
        
        private bool IsRecurringField;
        
        private int NumberOfRecurrencesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExecutionDate
        {
            get
            {
                return this.ExecutionDateField;
            }
            set
            {
                this.ExecutionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Frequency
        {
            get
            {
                return this.FrequencyField;
            }
            set
            {
                this.FrequencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecurring
        {
            get
            {
                return this.IsRecurringField;
            }
            set
            {
                this.IsRecurringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfRecurrences
        {
            get
            {
                return this.NumberOfRecurrencesField;
            }
            set
            {
                this.NumberOfRecurrencesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThreeDSecureDetails", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class ThreeDSecureDetails : object
    {
        
        private string AuthenticationResultField;
        
        private string CAVVField;
        
        private string ECIIndicatorField;
        
        private string TransactionStainField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationResult
        {
            get
            {
                return this.AuthenticationResultField;
            }
            set
            {
                this.AuthenticationResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CAVV
        {
            get
            {
                return this.CAVVField;
            }
            set
            {
                this.CAVVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ECIIndicator
        {
            get
            {
                return this.ECIIndicatorField;
            }
            set
            {
                this.ECIIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionStain
        {
            get
            {
                return this.TransactionStainField;
            }
            set
            {
                this.TransactionStainField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionDetails", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class TransactionDetails : object
    {
        
        private string AcquirerIdField;
        
        private string AmountField;
        
        private string CurrencyField;
        
        private int CurrencyExponentField;
        
        private string CustomDataField;
        
        private string IPAddressField;
        
        private string MerchantIdField;
        
        private string OrderNumberField;
        
        private string SignatureField;
        
        private string SignatureMethodField;
        
        private int TransactionCodeField;
        
        private string CustomerReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AcquirerId
        {
            get
            {
                return this.AcquirerIdField;
            }
            set
            {
                this.AcquirerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CurrencyExponent
        {
            get
            {
                return this.CurrencyExponentField;
            }
            set
            {
                this.CurrencyExponentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomData
        {
            get
            {
                return this.CustomDataField;
            }
            set
            {
                this.CustomDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress
        {
            get
            {
                return this.IPAddressField;
            }
            set
            {
                this.IPAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                this.MerchantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SignatureMethod
        {
            get
            {
                return this.SignatureMethodField;
            }
            set
            {
                this.SignatureMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TransactionCode
        {
            get
            {
                return this.TransactionCodeField;
            }
            set
            {
                this.TransactionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string CustomerReference
        {
            get
            {
                return this.CustomerReferenceField;
            }
            set
            {
                this.CustomerReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShippingDetails", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class ShippingDetails : object
    {
        
        private string ShipToAddressField;
        
        private string ShipToAddress2Field;
        
        private string ShipToCityField;
        
        private string ShipToCountryField;
        
        private string ShipToCountyField;
        
        private string ShipToEmailField;
        
        private string ShipToFirstNameField;
        
        private string ShipToLastNameField;
        
        private string ShipToMobileField;
        
        private string ShipToStateField;
        
        private string ShipToTelephoneField;
        
        private string ShipToZipPostCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToAddress
        {
            get
            {
                return this.ShipToAddressField;
            }
            set
            {
                this.ShipToAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToAddress2
        {
            get
            {
                return this.ShipToAddress2Field;
            }
            set
            {
                this.ShipToAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToCity
        {
            get
            {
                return this.ShipToCityField;
            }
            set
            {
                this.ShipToCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToCountry
        {
            get
            {
                return this.ShipToCountryField;
            }
            set
            {
                this.ShipToCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToCounty
        {
            get
            {
                return this.ShipToCountyField;
            }
            set
            {
                this.ShipToCountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToEmail
        {
            get
            {
                return this.ShipToEmailField;
            }
            set
            {
                this.ShipToEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToFirstName
        {
            get
            {
                return this.ShipToFirstNameField;
            }
            set
            {
                this.ShipToFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToLastName
        {
            get
            {
                return this.ShipToLastNameField;
            }
            set
            {
                this.ShipToLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToMobile
        {
            get
            {
                return this.ShipToMobileField;
            }
            set
            {
                this.ShipToMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToState
        {
            get
            {
                return this.ShipToStateField;
            }
            set
            {
                this.ShipToStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToTelephone
        {
            get
            {
                return this.ShipToTelephoneField;
            }
            set
            {
                this.ShipToTelephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToZipPostCode
        {
            get
            {
                return this.ShipToZipPostCodeField;
            }
            set
            {
                this.ShipToZipPostCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FraudDetails", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class FraudDetails : object
    {
        
        private string AVSResponseCodeField;
        
        private string AuthResponseCodeField;
        
        private string CVVResponseCodeField;
        
        private string SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AVSResponseCode
        {
            get
            {
                return this.AVSResponseCodeField;
            }
            set
            {
                this.AVSResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AuthResponseCode
        {
            get
            {
                return this.AuthResponseCodeField;
            }
            set
            {
                this.AuthResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CVVResponseCode
        {
            get
            {
                return this.CVVResponseCodeField;
            }
            set
            {
                this.CVVResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizeResponse", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class AuthorizeResponse : object
    {
        
        private string AcquirerIdField;
        
        private Services.BillingDetails BillingDetailsField;
        
        private Services.CreditCardTransactionResults CreditCardTransactionResultsField;
        
        private string CustomDataField;
        
        private Services.IPGeoLocationResults IPGeoLocationResultsField;
        
        private string MerchantIdField;
        
        private string OrderNumberField;
        
        private string SignatureField;
        
        private string SignatureMethodField;
        
        private Services.BinCheckResults BinCheckResultsField;
        
        private Services.FraudControlResults FraudControlResultsField;
        
        private Services.ShippingDetails ShippingDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcquirerId
        {
            get
            {
                return this.AcquirerIdField;
            }
            set
            {
                this.AcquirerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.BillingDetails BillingDetails
        {
            get
            {
                return this.BillingDetailsField;
            }
            set
            {
                this.BillingDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.CreditCardTransactionResults CreditCardTransactionResults
        {
            get
            {
                return this.CreditCardTransactionResultsField;
            }
            set
            {
                this.CreditCardTransactionResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomData
        {
            get
            {
                return this.CustomDataField;
            }
            set
            {
                this.CustomDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.IPGeoLocationResults IPGeoLocationResults
        {
            get
            {
                return this.IPGeoLocationResultsField;
            }
            set
            {
                this.IPGeoLocationResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                this.MerchantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureMethod
        {
            get
            {
                return this.SignatureMethodField;
            }
            set
            {
                this.SignatureMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public Services.BinCheckResults BinCheckResults
        {
            get
            {
                return this.BinCheckResultsField;
            }
            set
            {
                this.BinCheckResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public Services.FraudControlResults FraudControlResults
        {
            get
            {
                return this.FraudControlResultsField;
            }
            set
            {
                this.FraudControlResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public Services.ShippingDetails ShippingDetails
        {
            get
            {
                return this.ShippingDetailsField;
            }
            set
            {
                this.ShippingDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardTransactionResults", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class CreditCardTransactionResults : object
    {
        
        private string AVSResultField;
        
        private string AuthCodeField;
        
        private string CVV2ResultField;
        
        private string OriginalResponseCodeField;
        
        private string PaddedCardNumberField;
        
        private string ReasonCodeField;
        
        private string ReasonCodeDescriptionField;
        
        private string ReferenceNumberField;
        
        private string ResponseCodeField;
        
        private string TokenizedPANField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AVSResult
        {
            get
            {
                return this.AVSResultField;
            }
            set
            {
                this.AVSResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode
        {
            get
            {
                return this.AuthCodeField;
            }
            set
            {
                this.AuthCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV2Result
        {
            get
            {
                return this.CVV2ResultField;
            }
            set
            {
                this.CVV2ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalResponseCode
        {
            get
            {
                return this.OriginalResponseCodeField;
            }
            set
            {
                this.OriginalResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaddedCardNumber
        {
            get
            {
                return this.PaddedCardNumberField;
            }
            set
            {
                this.PaddedCardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCodeDescription
        {
            get
            {
                return this.ReasonCodeDescriptionField;
            }
            set
            {
                this.ReasonCodeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenizedPAN
        {
            get
            {
                return this.TokenizedPANField;
            }
            set
            {
                this.TokenizedPANField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IPGeoLocationResults", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class IPGeoLocationResults : object
    {
        
        private string CityField;
        
        private string CountryLongField;
        
        private string CountryShortField;
        
        private string DomainNameField;
        
        private string IPAddressField;
        
        private string IPResponseCodeField;
        
        private string IPResponseCodeDescriptionField;
        
        private string ISPField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string RegionField;
        
        private string TimeZoneField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryLong
        {
            get
            {
                return this.CountryLongField;
            }
            set
            {
                this.CountryLongField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryShort
        {
            get
            {
                return this.CountryShortField;
            }
            set
            {
                this.CountryShortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DomainName
        {
            get
            {
                return this.DomainNameField;
            }
            set
            {
                this.DomainNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress
        {
            get
            {
                return this.IPAddressField;
            }
            set
            {
                this.IPAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPResponseCode
        {
            get
            {
                return this.IPResponseCodeField;
            }
            set
            {
                this.IPResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPResponseCodeDescription
        {
            get
            {
                return this.IPResponseCodeDescriptionField;
            }
            set
            {
                this.IPResponseCodeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISP
        {
            get
            {
                return this.ISPField;
            }
            set
            {
                this.ISPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeZone
        {
            get
            {
                return this.TimeZoneField;
            }
            set
            {
                this.TimeZoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BinCheckResults", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class BinCheckResults : object
    {
        
        private string BINField;
        
        private string BrandField;
        
        private string CountryField;
        
        private string IssuerField;
        
        private string SubtypeField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BIN
        {
            get
            {
                return this.BINField;
            }
            set
            {
                this.BINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand
        {
            get
            {
                return this.BrandField;
            }
            set
            {
                this.BrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issuer
        {
            get
            {
                return this.IssuerField;
            }
            set
            {
                this.IssuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subtype
        {
            get
            {
                return this.SubtypeField;
            }
            set
            {
                this.SubtypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FraudControlResults", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class FraudControlResults : object
    {
        
        private string FraudControlIdField;
        
        private string FraudResponseCodeField;
        
        private string ReasonCodeField;
        
        private string ReasonCodeDescField;
        
        private string ResponseCodeField;
        
        private string ScoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FraudControlId
        {
            get
            {
                return this.FraudControlIdField;
            }
            set
            {
                this.FraudControlIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FraudResponseCode
        {
            get
            {
                return this.FraudResponseCodeField;
            }
            set
            {
                this.FraudResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCodeDesc
        {
            get
            {
                return this.ReasonCodeDescField;
            }
            set
            {
                this.ReasonCodeDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionModificationRequest", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class TransactionModificationRequest : object
    {
        
        private string AcquirerIdField;
        
        private string AmountField;
        
        private int CurrencyExponentField;
        
        private string MerchantIdField;
        
        private int ModificationTypeField;
        
        private string OrderNumberField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcquirerId
        {
            get
            {
                return this.AcquirerIdField;
            }
            set
            {
                this.AcquirerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyExponent
        {
            get
            {
                return this.CurrencyExponentField;
            }
            set
            {
                this.CurrencyExponentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                this.MerchantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModificationType
        {
            get
            {
                return this.ModificationTypeField;
            }
            set
            {
                this.ModificationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionModificationResponse", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class TransactionModificationResponse : object
    {
        
        private string AcquirerIdField;
        
        private string MerchantIdField;
        
        private string OrderNumberField;
        
        private string OriginalResponseCodeField;
        
        private string ReasonCodeField;
        
        private string ReasonCodeDescriptionField;
        
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcquirerId
        {
            get
            {
                return this.AcquirerIdField;
            }
            set
            {
                this.AcquirerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                this.MerchantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalResponseCode
        {
            get
            {
                return this.OriginalResponseCodeField;
            }
            set
            {
                this.OriginalResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCodeDescription
        {
            get
            {
                return this.ReasonCodeDescriptionField;
            }
            set
            {
                this.ReasonCodeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authorize3DSRequest", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class Authorize3DSRequest : object
    {
        
        private Services.BillingDetails BillingDetailsField;
        
        private Services.CardDetails CardDetailsField;
        
        private string MerchantResponseURLField;
        
        private Services.TransactionDetails TransactionDetailsField;
        
        private Services.RecurringDetails RecurringDetailsField;
        
        private Services.FraudDetails FraudDetailsField;
        
        private Services.ShippingDetails ShippingDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.BillingDetails BillingDetails
        {
            get
            {
                return this.BillingDetailsField;
            }
            set
            {
                this.BillingDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.CardDetails CardDetails
        {
            get
            {
                return this.CardDetailsField;
            }
            set
            {
                this.CardDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantResponseURL
        {
            get
            {
                return this.MerchantResponseURLField;
            }
            set
            {
                this.MerchantResponseURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.TransactionDetails TransactionDetails
        {
            get
            {
                return this.TransactionDetailsField;
            }
            set
            {
                this.TransactionDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Services.RecurringDetails RecurringDetails
        {
            get
            {
                return this.RecurringDetailsField;
            }
            set
            {
                this.RecurringDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Services.FraudDetails FraudDetails
        {
            get
            {
                return this.FraudDetailsField;
            }
            set
            {
                this.FraudDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Services.ShippingDetails ShippingDetails
        {
            get
            {
                return this.ShippingDetailsField;
            }
            set
            {
                this.ShippingDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authorize3DSResponse", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class Authorize3DSResponse : object
    {
        
        private string HTMLFormDataField;
        
        private string ResponseCodeField;
        
        private string ResponseCodeDescriptionField;
        
        private string TokenizedPANField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTMLFormData
        {
            get
            {
                return this.HTMLFormDataField;
            }
            set
            {
                this.HTMLFormDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCodeDescription
        {
            get
            {
                return this.ResponseCodeDescriptionField;
            }
            set
            {
                this.ResponseCodeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenizedPAN
        {
            get
            {
                return this.TokenizedPANField;
            }
            set
            {
                this.TokenizedPANField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IPGeoLocationRequest", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class IPGeoLocationRequest : object
    {
        
        private string IPAddressField;
        
        private string MerchantIdField;
        
        private string OrderNumberField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress
        {
            get
            {
                return this.IPAddressField;
            }
            set
            {
                this.IPAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                this.MerchantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IPGeoLocationResponse", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class IPGeoLocationResponse : object
    {
        
        private Services.IPGeoLocationResults IPGeoLocationDetailsField;
        
        private string MerchantIdField;
        
        private string OrderNumberField;
        
        private string SignatureField;
        
        private string SignatureMethodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.IPGeoLocationResults IPGeoLocationDetails
        {
            get
            {
                return this.IPGeoLocationDetailsField;
            }
            set
            {
                this.IPGeoLocationDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                this.MerchantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureMethod
        {
            get
            {
                return this.SignatureMethodField;
            }
            set
            {
                this.SignatureMethodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionStatusRequest", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class TransactionStatusRequest : object
    {
        
        private string AcquirerIdField;
        
        private string MerchantIdField;
        
        private string OrderNumberField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcquirerId
        {
            get
            {
                return this.AcquirerIdField;
            }
            set
            {
                this.AcquirerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                this.MerchantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionStatusResponse", Namespace="http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class TransactionStatusResponse : object
    {
        
        private string AcquirerIdField;
        
        private Services.CreditCardTransactionResults CreditCardTransactionResultsField;
        
        private string CustomDataField;
        
        private string MerchantIdField;
        
        private string OrderNumberField;
        
        private string SignatureField;
        
        private string SignatureMethodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcquirerId
        {
            get
            {
                return this.AcquirerIdField;
            }
            set
            {
                this.AcquirerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.CreditCardTransactionResults CreditCardTransactionResults
        {
            get
            {
                return this.CreditCardTransactionResultsField;
            }
            set
            {
                this.CreditCardTransactionResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomData
        {
            get
            {
                return this.CustomDataField;
            }
            set
            {
                this.CustomDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                this.MerchantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureMethod
        {
            get
            {
                return this.SignatureMethodField;
            }
            set
            {
                this.SignatureMethodField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.firstatlanticcommerce.com/gateway", ConfigurationName="Services.IServices")]
    public interface IServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/IServices/Authorize", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/IServices/AuthorizeResponse")]
        System.Threading.Tasks.Task<Services.AuthorizeResponse> AuthorizeAsync(Services.AuthorizeRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/IServices/TransactionModificatio" +
            "n", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/IServices/TransactionModificatio" +
            "nResponse")]
        System.Threading.Tasks.Task<Services.TransactionModificationResponse> TransactionModificationAsync(Services.TransactionModificationRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/IServices/Authorize3DS", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/IServices/Authorize3DSResponse")]
        System.Threading.Tasks.Task<Services.Authorize3DSResponse> Authorize3DSAsync(Services.Authorize3DSRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/IServices/IPGeoLocation", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/IServices/IPGeoLocationResponse")]
        System.Threading.Tasks.Task<Services.IPGeoLocationResponse> IPGeoLocationAsync(Services.IPGeoLocationRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.firstatlanticcommerce.com/gateway/IServices/TransactionStatus", ReplyAction="http://schemas.firstatlanticcommerce.com/gateway/IServices/TransactionStatusRespo" +
            "nse")]
        System.Threading.Tasks.Task<Services.TransactionStatusResponse> TransactionStatusAsync(Services.TransactionStatusRequest Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServicesChannel : Services.IServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<Services.IServices>, Services.IServices
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicesClient() : 
                base(ServicesClient.GetDefaultBinding(), ServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicesClient.GetBindingForEndpoint(endpointConfiguration), ServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Services.AuthorizeResponse> AuthorizeAsync(Services.AuthorizeRequest Request)
        {
            return base.Channel.AuthorizeAsync(Request);
        }
        
        public System.Threading.Tasks.Task<Services.TransactionModificationResponse> TransactionModificationAsync(Services.TransactionModificationRequest Request)
        {
            return base.Channel.TransactionModificationAsync(Request);
        }
        
        public System.Threading.Tasks.Task<Services.Authorize3DSResponse> Authorize3DSAsync(Services.Authorize3DSRequest Request)
        {
            return base.Channel.Authorize3DSAsync(Request);
        }
        
        public System.Threading.Tasks.Task<Services.IPGeoLocationResponse> IPGeoLocationAsync(Services.IPGeoLocationRequest Request)
        {
            return base.Channel.IPGeoLocationAsync(Request);
        }
        
        public System.Threading.Tasks.Task<Services.TransactionStatusResponse> TransactionStatusAsync(Services.TransactionStatusRequest Request)
        {
            return base.Channel.TransactionStatusAsync(Request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServices))
            {
                return new System.ServiceModel.EndpointAddress("https://marlin.firstatlanticcommerce.com/PGService/Services.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServices,
        }
    }
}
