//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokenization
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TokenizeRequest", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class TokenizeRequest : object
    {

        private string CardNumberField;

        private string CustomerReferenceField;

        private string ExpiryDateField;

        private string MerchantNumberField;

        private string SignatureField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CustomerReference
        {
            get
            {
                return this.CustomerReferenceField;
            }
            set
            {
                this.CustomerReferenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string MerchantNumber
        {
            get
            {
                return this.MerchantNumberField;
            }
            set
            {
                this.MerchantNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TokenizeResponse", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class TokenizeResponse : object
    {

        private string ErrorMsgField;

        private bool SuccessField;

        private string TokenField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg
        {
            get
            {
                return this.ErrorMsgField;
            }
            set
            {
                this.ErrorMsgField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DeTokenizeRequest", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class DeTokenizeRequest : object
    {

        private string MerchantNumberField;

        private string SignatureField;

        private string TokenPANField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantNumber
        {
            get
            {
                return this.MerchantNumberField;
            }
            set
            {
                this.MerchantNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenPAN
        {
            get
            {
                return this.TokenPANField;
            }
            set
            {
                this.TokenPANField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DeTokenizeResponse", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class DeTokenizeResponse : object
    {

        private string ErrorMsgField;

        private string ExpiryDateField;

        private string PANField;

        private bool SuccessField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg
        {
            get
            {
                return this.ErrorMsgField;
            }
            set
            {
                this.ErrorMsgField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAN
        {
            get
            {
                return this.PANField;
            }
            set
            {
                this.PANField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TokenListRequest", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class TokenListRequest : object
    {

        private string CustomerReferenceField;

        private string MerchantNumberField;

        private string SignatureField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerReference
        {
            get
            {
                return this.CustomerReferenceField;
            }
            set
            {
                this.CustomerReferenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantNumber
        {
            get
            {
                return this.MerchantNumberField;
            }
            set
            {
                this.MerchantNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TokenListResponse", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class TokenListResponse : object
    {

        private TokenizedCard[] CardListField;

        private string ErrorMsgField;

        private bool SuccessField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public TokenizedCard[] CardList
        {
            get
            {
                return this.CardListField;
            }
            set
            {
                this.CardListField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg
        {
            get
            {
                return this.ErrorMsgField;
            }
            set
            {
                this.ErrorMsgField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TokenizedCard", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class TokenizedCard : object
    {

        private string CustomerReferenceField;

        private string ExpiryDateField;

        private string TokenPANField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerReference
        {
            get
            {
                return this.CustomerReferenceField;
            }
            set
            {
                this.CustomerReferenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenPAN
        {
            get
            {
                return this.TokenPANField;
            }
            set
            {
                this.TokenPANField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UpdateTokenRequest", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class UpdateTokenRequest : object
    {

        private string CustomerReferenceField;

        private string ExpiryDateField;

        private string MerchantNumberField;

        private string SignatureField;

        private string TokenPANField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CustomerReference
        {
            get
            {
                return this.CustomerReferenceField;
            }
            set
            {
                this.CustomerReferenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string MerchantNumber
        {
            get
            {
                return this.MerchantNumberField;
            }
            set
            {
                this.MerchantNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string TokenPAN
        {
            get
            {
                return this.TokenPANField;
            }
            set
            {
                this.TokenPANField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UpdateTokenResponse", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class UpdateTokenResponse : object
    {

        private string ErrorMsgField;

        private bool SuccessField;

        private string TokenPANField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg
        {
            get
            {
                return this.ErrorMsgField;
            }
            set
            {
                this.ErrorMsgField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenPAN
        {
            get
            {
                return this.TokenPANField;
            }
            set
            {
                this.TokenPANField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ExpiringCreditCardsRequest", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class ExpiringCreditCardsRequest : object
    {

        private string EndDateField;

        private string ExpiryDateField;

        private string MerchantIdField;

        private string SignatureField;

        private string StartDateField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                this.MerchantIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ExpiringCreditCardsResponse", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class ExpiringCreditCardsResponse : object
    {

        private string ErrorMessageField;

        private ExpiringCreditCard[] ExpiringCreditCardsField;

        private bool SuccessField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExpiringCreditCard[] ExpiringCreditCards
        {
            get
            {
                return this.ExpiringCreditCardsField;
            }
            set
            {
                this.ExpiringCreditCardsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ExpiringCreditCard", Namespace = "http://schemas.firstatlanticcommerce.com/gateway/data")]
    public partial class ExpiringCreditCard : object
    {

        private string CustomerIdField;

        private string ExpiryDateField;

        private string MaskedPANField;

        private string TokenCodeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaskedPAN
        {
            get
            {
                return this.MaskedPANField;
            }
            set
            {
                this.MaskedPANField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenCode
        {
            get
            {
                return this.TokenCodeField;
            }
            set
            {
                this.TokenCodeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://schemas.firstatlanticcommerce.com/gateway", ConfigurationName = "Tokenization.Tokenization")]
    public interface Tokenization
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.firstatlanticcommerce.com/gateway/Tokenization/Tokenize", ReplyAction = "http://schemas.firstatlanticcommerce.com/gateway/Tokenization/TokenizeResponse")]
        System.Threading.Tasks.Task<TokenizeResponse> TokenizeAsync(TokenizeRequest Request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.firstatlanticcommerce.com/gateway/Tokenization/DeTokenize", ReplyAction = "http://schemas.firstatlanticcommerce.com/gateway/Tokenization/DeTokenizeResponse")]
        System.Threading.Tasks.Task<DeTokenizeResponse> DeTokenizeAsync(DeTokenizeRequest Request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.firstatlanticcommerce.com/gateway/Tokenization/TokenList", ReplyAction = "http://schemas.firstatlanticcommerce.com/gateway/Tokenization/TokenListResponse")]
        System.Threading.Tasks.Task<TokenListResponse> TokenListAsync(TokenListRequest Request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.firstatlanticcommerce.com/gateway/Tokenization/UpdateToken", ReplyAction = "http://schemas.firstatlanticcommerce.com/gateway/Tokenization/UpdateTokenResponse" +
            "")]
        System.Threading.Tasks.Task<UpdateTokenResponse> UpdateTokenAsync(UpdateTokenRequest Request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://schemas.firstatlanticcommerce.com/gateway/Tokenization/ExpiringCreditCards" +
            "", ReplyAction = "http://schemas.firstatlanticcommerce.com/gateway/Tokenization/ExpiringCreditCards" +
            "Response")]
        System.Threading.Tasks.Task<ExpiringCreditCardsResponse> ExpiringCreditCardsAsync(ExpiringCreditCardsRequest Request);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface TokenizationChannel : Tokenization, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class TokenizationClient : System.ServiceModel.ClientBase<Tokenization>, Tokenization
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public TokenizationClient() :
                base(TokenizationClient.GetDefaultBinding(), TokenizationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_Tokenization.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public TokenizationClient(EndpointConfiguration endpointConfiguration) :
                base(TokenizationClient.GetBindingForEndpoint(endpointConfiguration), TokenizationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public TokenizationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(TokenizationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public TokenizationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(TokenizationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public TokenizationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<TokenizeResponse> TokenizeAsync(TokenizeRequest Request)
        {
            return base.Channel.TokenizeAsync(Request);
        }

        public System.Threading.Tasks.Task<DeTokenizeResponse> DeTokenizeAsync(DeTokenizeRequest Request)
        {
            return base.Channel.DeTokenizeAsync(Request);
        }

        public System.Threading.Tasks.Task<TokenListResponse> TokenListAsync(TokenListRequest Request)
        {
            return base.Channel.TokenListAsync(Request);
        }

        public System.Threading.Tasks.Task<UpdateTokenResponse> UpdateTokenAsync(UpdateTokenRequest Request)
        {
            return base.Channel.UpdateTokenAsync(Request);
        }

        public System.Threading.Tasks.Task<ExpiringCreditCardsResponse> ExpiringCreditCardsAsync(ExpiringCreditCardsRequest Request)
        {
            return base.Channel.ExpiringCreditCardsAsync(Request);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Tokenization))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Tokenization))
            {
                return new System.ServiceModel.EndpointAddress("https://ecm.firstatlanticcommerce.com/PGService/Tokenization.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TokenizationClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_Tokenization);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TokenizationClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_Tokenization);
        }

        public enum EndpointConfiguration
        {

            BasicHttpBinding_Tokenization,
        }
    }
}
